import {FC, PropsWithChildren} from "react";
import Head from "next/head";
import NavBar from "../NavBar/NavBar";
import styles from "./MainLayouts.module.css";

export interface Props {children: React.ReactNode}

export const MainLayouts: FC<Props>  = ({ children }) => {
  return (
    <>
      <NavBar />
      <div className={styles.container}>
        <Head>
          <title> Jose Gutierrez - Home </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>{children}</main>
      </div>
    </>
  );
};
